### ISSUE TITLE
Scorecard page (for purpose of automating getting scorecard items)

### ISSUE THREAD

**Issue by ezl** [howdykolache/admin#60]
Create a single page that shows some stats:

1. total number of kolaches ordered in the last week (basically sum of all counts in last 7 days), by category (so should be a table, with a row for each category type, then a total)
2. total number of ORDERS in the last week (same thing)

Example:

## Kolaches ordered

Coffee shops 3200
Bars 200
Catering 250
Demo boxes 80

## Orders

Coffee shops 91
Bars 4
Catering 11
Demo boxes 12

**Comment by niall-p-gray** [comment]
Hi @ezl, I've got a link for testing below, and from what I can see it's working pretty consistently: https://script.google.com/macros/s/AKfycbypWcf96AUOovVPtLuYAUOkpr6kzbSBL9fYFC4LEbK4KrS6bW97V-nxeJDhMJJNxKk/exec?mode=scorecard

Apologies in advance but I just want to run through my logic with you as I'm finding that dates muddle me and I can't get my head around how this should all be working. With this for the sake of me not getting more confused I'd like to request that you use similar terms to the ones I've used below if I've got any of the behaviors wrong, as this will help me to get it right.

So in looking at the pre-defined date ranges I've used two different formulas for the past and future ones (I don't know if this is right, but in both cases I've tried to include the present day's orders as that seemed intuitive to me)... with this I'll split up and give the rule I applied:

**Past Orders**
Collated orders are for *AFTER* today's date minus n no. of days and *ON OR BEFORE* the current date 
![image](https://user-images.githubusercontent.com/96024810/188988578-31b88316-bb98-479a-89da-748fb9feb0c2.png)

**Future Orders**
Collated orders are *ON OR AFTER* the current date and *BEFORE* the current date plus n. no of days
![image](https://user-images.githubusercontent.com/96024810/188989319-94635835-021f-479a-92b7-cac5b294b43a.png)

In both cases this amounts to me taking the present day's orders and walking forward or backwards n-1 times (as the present day is day 1) and summing all of those daily orders. E.g. if the user chooses the 'Past 7 Days' radio button it's like me taking today's orders and walking back six days and summing everything up.

I think I'm overcomplicating this is my head, but I just want to make sure I'm aligned with your expectations as to me there are ambiguities on what this could all mean.

**Comment by niall-p-gray** [comment]
Current behavior approved by Eric over Slack so will change to for review.

**Comment by ezl** [comment]
@niall-p-gray this is good with the total summary, but i only see it in the link you sent - can you deploy to production please?

**Comment by niall-p-gray** [comment]
@ezl, this is in the toc under the 'Production Team Links' section using the title 'Scorecard' - if this needs changing in any way (title or position/section) please let me know.

**Comment by ezl** [comment]
@niall-p-gray i see it now. this is good. i'm closing the ticket
