### ISSUE TITLE
Admin order creation page - On successful submit, clear the entire form (or refresh page)

### ISSUE THREAD

**Issue by ezl** [howdykolache/admin#64]
- "admin order creation" - redirect to success page - send to new page with no functionality. basically just simple text that just says: "order created"(or order updated) for client: ____ on date ____.  link: back to dashboard. create new order.

**Comment by niall-p-gray** [comment]
https://script.google.com/macros/s/AKfycbxzGBGxZ4duz_qBBcjHse0j7p9HsfEJ35l8iUZaZDTy0W1bPmZkZ8uQ_YMKwCu8gK1xDQ/exec?mode=groupOrder

If the above link looks okay I can deploy to the real link ASAP. Otherwise if there are any tweaks required please let me know.

**Comment by ezl** [comment]
@niall-p-gray looks good please deploy
