### ISSUE TITLE
upcoming orders page modificaitons

### ISSUE THREAD

**Issue by ezl** [howdykolache/admin#67]
- [x] upcoming orders - only show future orders
- [ ] change the icon to text "expand / collapse"
- [ ] look into daily total value on "upcoming orders"

(updated to check off "show only future orders" because this is a priority task and I escalated it in a separate ticket)

**Comment by ezl** [comment]
x

**Comment by niall-p-gray** [comment]
Hi Eric, I've made some adjustments and think I've tackled each of these here: https://script.google.com/macros/s/AKfycbxaw_icAo4ftq0f3ifXq9TiMhezk5RW0H23SmohUKVfcXjid1qHWXvKAuLx1VP2BlFn/exec?mode=deliverySummary

If this looks good I can deploy to the live pages ASAP.

**Comment by niall-p-gray** [comment]
hi @ezl, I've just spotted that filtering the totals don't adjust when I filter the data, so I'll tweak this bit and send a new link shortly.

**Comment by niall-p-gray** [comment]
https://script.google.com/macros/s/AKfycbxqAp1YapUXrvk4IDxYF8gDe54Cnwj813PGg6jQ0tS3zwkM2s2U2EDeb8CsF4xmZLWo/exec?mode=deliverySummary

Besides the above points I've also adjusted the client types checkboxes to enable/disable based on the admin orders only checkbox value (previously all originally available client types would stay on regardless of the admin only checkbox value, but now it will disable them if the client type is no longer available when the admin only input is checked)

**Comment by ezl** [comment]
This is perfect. Thanks @niall-p-gray

**Comment by ezl** [comment]
@niall-p-gray if this isn't already live, please publish to the production version

**Comment by niall-p-gray** [comment]
@ezl, will do now :)
