### ISSUE TITLE
add delivery time (currently we have "ready for pickup" time) to admin order creation and upcoming orders page

### ISSUE THREAD

**Issue by ezl** [howdykolache/admin#73]

**Comment by niall-p-gray** [comment]
Order Page: https://script.google.com/a/macros/howdykolache.com/s/AKfycbwHsiQJllk9_PZTbnqzMEaOxm-jOIEeOfVKMBY875ClYVEfU35cOYYwy_eSkkoskXLGHg/exec?mode=groupOrder

Upcoming Orders Page: https://script.google.com/macros/s/AKfycbz2TOiFeVr9nt-izsGWaDhGCSZeW-Wb6Pds-NXOb6bSCNpLWakFLP2ExHIEDyDoNiMC/exec?mode=deliverySummary

Pages already deployed to TOC page, but happy making changes as needed.

**Comment by ezl** [comment]
@niall-p-gray same - this is fully checked off. I believe it is already live, but if not, please proceed

**Comment by niall-p-gray** [comment]
These should be deployed @ezl, but please give me a shout if you're not seeing at your side.

**Comment by ezl** [comment]
they look good. I used them yesterday already. Thanks @niall-p-gray  - Closing ticket.
