### ISSUE TITLE
Create a page called "all orders summary" - this is an exact clone of "delivery summary page" as it currently is (because the "delivery summary" will change to be ONLY recurring wholesale client orders)

### ISSUE THREAD

**Issue by ezl** [howdykolache/admin#75]

**Comment by niall-p-gray** [comment]
New page link added to TOC. If you need to differentiate between admin + wholesale orders please let me know... currently the sums are performed at date + client level, so if there are multiple order groups for a client (could be a wholesale + admin, or multiple admins) the page will just aggregate everything. There's also currently no attention paid to delivery addresses from the admin form page (it just grabs from the client address field)... if all of the above points are fine then the page is good to go, but I just wanted to raise in case any of these implications means the behavior needs tweaking.

**Comment by ezl** [comment]
This is executed perfectly as is. You've nailed it. Future updates will be new tickets. Thanks @niall-p-gray 

For now no need for the differentiation - aggregation at the client level is perfect for this use case.
