### ISSUE TITLE
on client creation page - automatically pre-select all items as available for the client + automatically select all delivery days

### ISSUE THREAD

**Issue by ezl** [howdykolache/admin#77]
@niall-p-gray do the delivery days and available items impact users who are entered via "Admin Order Creation"? (I don't think they do, and i don't need/want them to be)

**Comment by niall-p-gray** [comment]
hi @ezl, the admin order page allows access to all products and doesn't restrict the date regardless of the restrictions placed when building/editing a client record.

**Comment by ezl** [comment]
@niall-p-gray got it. ok, then no need to make any changes on client creation page. 

This ticket is no longer necessary.
