### ISSUE TITLE
change password to "howdyhowdy"

### ISSUE THREAD

**Issue by ezl** [howdykolache/admin#79]

**Comment by niall-p-gray** [comment]
Ready for review.

**Comment by ezl** [comment]
@niall-p-gray - it looks to me like this is no longer requiring a password at all.

i opened a new browser that had NOT authenticated and just went to `admin.howdykolache.com` - without being prompted for a password, the page contents were displayed to me.

Can you check to see if you see the same please?

**Comment by niall-p-gray** [comment]
hi @ezl, can you check that the toc page url in the admin.howdykolache.com page uses the following? https://script.google.com/a/macros/howdykolache.com/s/AKfycbyRlkWIyffqJPN-ODZ8VC-jYXiNE7_CEVHfhhiZqDWxewdgi0WNS58YBXOmm55nsvVDNA/exec ... I tried on a private window of firefox to make sure I'd not input the pass before and I a) received the password prompt screen and b) only got through in typing the new howdyhowdy password... I tried the admin.howdykolache.com link and am getting the same behavior that you are so my best guess is that the admin page is using an old deployment url... if this is the case this is likely my bad as I may not have updated the link you're using on the admin page, but hopefully this will allow for a quick fix if that's the case. If not, I'll do some digging and see what I can come up with.

**Comment by ezl** [comment]
I'm not quite sure what's going on, because now it seems to be working as expected.

i'm going guess that your theory about the old page explains it, so now it's fine :) 

Closing ticket. if it comes back, I'll create a new one
