### ISSUE TITLE
[Admin Order Creation] Add an optional text field after client selection for "Client Details"

### ISSUE THREAD

**Issue by ezl** [howdykolache/admin#81]
This will be a select field that also accepts new values. The use case for this is:

Eric Samples: Next Finance
Eric Samples: CTC Trading
Eric Samples: Ankin Law

or

ezCater: Jump Trading
ezCater: Origami Risk

etc

Add help text: "For example, if the main client is an intermediary (samples, ezCater, etc) - Please use this field to enter the actual client"

**Comment by niall-p-gray** [comment]
Order Page Link: https://script.google.com/a/macros/howdykolache.com/s/AKfycbwHsiQJllk9_PZTbnqzMEaOxm-jOIEeOfVKMBY875ClYVEfU35cOYYwy_eSkkoskXLGHg/exec?mode=groupOrder

Upcoming Orders Page: https://script.google.com/macros/s/AKfycbwWCkZnTiFgh4Xm8NKL4F5Cw8tonn9TS1hn000Gu0fUpuDokRhG1nX5C-_mfmUvAu1-/exec?mode=deliverySummary

On the upcoming orders page client details will be displayed beneath the client name in the same column and split using a colon as per the screenshot below... if this needs changing in any way though just let me know and I'll tweak to your preference.



![Image](https://user-images.githubusercontent.com/96024810/194179177-62550a3b-864c-47c2-aeb9-00e03682e1ac.png)

**Comment by ezl** [comment]
@niall-p-gray these are perfect. I think they are already deployed (pretty sure I saw them in production yesterday), but if not, please do whatever necessary to complete deployment to production

**Comment by niall-p-gray** [comment]
These should be deployed @ezl, but please give me a shout if you're not seeing at your side.

**Comment by ezl** [comment]
they look good. I used them yesterday already. Thanks @niall-p-gray  - Closing ticket.
