### ISSUE TITLE
High priority: Create new page "Coffee Shops & Bars Packing Summary By Day"

### ISSUE THREAD

**Issue by ezl** [howdykolache/admin#85]
Create a new page in admin called "Coffee Shops & Bars Packing Summary By Day".

This will go under the "Delivery Links" section.

This should be relatively straightforward. No styling necessary.

This page will contain a total count of all the items for coffee shops and bars for the selected day.

It should be a table of columns:

```
Product              | Total # (8 packs)     |     Total #        |      Items NOT divisible by 8
Colorodough     |         25                      |      200           |                         
Ron Swanson    |         17                       |       136          |                         
El Greco            |          27                      |       216          |                         
KREAM             |           10.25                 |       82            |                        2, 4, 4

```

Video of me describing this a bit more
https://www.loom.com/share/1bd11f8c2f174359b4eee69b734b5087

**Comment by niall-p-gray** [comment]
Page created and added to the Airtable TOC grid: https://script.google.com/macros/s/AKfycby7a4VbO8kTmdg99FJOo-1MDZ_6cmJmsacRaGioEiJfMcFO6SltgqL9WeAoL6HPmjdxVw/exec?mode=packingPlanner

If you have any notes/changes please let me know.

**Comment by niall-p-gray** [comment]
Page created and added to the Airtable TOC grid: https://script.google.com/macros/s/AKfycby7a4VbO8kTmdg99FJOo-1MDZ_6cmJmsacRaGioEiJfMcFO6SltgqL9WeAoL6HPmjdxVw/exec?mode=packingPlanner

If you have any notes/changes please let me know.

**Comment by ezl** [comment]
This looks very good, @niall-p-gray -

I think this is pulling in orders from clients of all types (or at least coffee shop + bar  + DEMO BOX) - for the purposes of this, I only need coffee shops and bars, as extra "non-divisible by 8" types are making it into here.

Can we just do coffee shops and bars, and divide those into 2 sections (basically repeat the table twice. once for coffee shops, once for bars)

https://www.loom.com/share/66cde9e9e8d248c680eeebbb711ab5c9

**Comment by niall-p-gray** [comment]
@ezl, will check out the filters applied to this particular page, and yep, I can split the counts up by client type... will aim to update tonight, but if not should definitely be doable by tomorrow evening

**Comment by ezl** [comment]
@niall-p-gray no crazy rush on this one - tomorrow is more than fast enough. thanks @niall-p-gray

**Comment by niall-p-gray** [comment]
Hi @ezl, apologies for the wait, but I think I've managed to fix both the coffee shop/bar filtering issue and have managed to group the orders by client type. If you have any other bits that need tweaking or the numbers are still looking a little off, feel free to give me a shout.

**Comment by niall-p-gray** [comment]
...sorry, forgot to include a link: https://script.google.com/macros/s/AKfycby7a4VbO8kTmdg99FJOo-1MDZ_6cmJmsacRaGioEiJfMcFO6SltgqL9WeAoL6HPmjdxVw/exec?mode=packingPlanner

**Comment by ezl** [comment]
looks good! closing!
